# Generated by Django 5.0.2 on 2024-03-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="groups",
            field=models.ManyToManyField(related_name="workers", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task_manager.position",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="workers_permissions", to="auth.permission"
            ),
        ),
    ]
