# Generated by Django 4.2.11 on 2024-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_groups_alter_worker_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High", "High"),
                    ("Ordinary", "Ordinary"),
                    ("Low", "Low"),
                ],
                default="Ordinary",
                max_length=10,
            ),
        ),
    ]
