# Generated by Django 5.0.3 on 2024-03-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("task_manager", "0004_uservisit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees_list",
            field=models.ManyToManyField(
                related_name="tasks", to="task_manager.worker"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_manager.tasktype",
            ),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="user_permissions",
            field=models.ManyToManyField(related_name="workers", to="auth.permission"),
        ),
    ]
