# Generated by Django 5.0.3 on 2024-03-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager",
            "0005_alter_task_assignees_list_alter_task_task_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_visits",
                to="task_manager.worker",
            ),
        ),
    ]
